# Generated by Django 3.2.7 on 2021-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.ManyToManyField(to='recipe.Ingredients'),
        ),
    ]
