# Generated by Django 3.2.7 on 2021-09-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210922_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_list',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
