# Generated by Django 3.2.7 on 2021-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0003_auto_20210922_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=200)),
                ('diet', models.CharField(max_length=50)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('flavor_profile', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('ingredients_list', models.CharField(max_length=200)),
            ],
        ),
    ]
