# Generated by Django 3.2.7 on 2021-10-05 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_image_pantry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='result',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='pantry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.category'),
        ),
        migrations.DeleteModel(
            name='Pantry',
        ),
    ]
